name: Update Traffic Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch: 
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Get Traffic Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CLONES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/YOUR_USERNAME/YOUR_REPO_NAME/traffic/clones" | jq '.count')
          VISITS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/YOUR_USERNAME/YOUR_REPO_NAME/traffic/views" | jq '.count')
          
          echo "Clones: $CLONES"
          echo "Visits: $VISITS"
          
          # Replace placeholders in README.md
          sed -i "s/{CLONES}/$CLONES/" README.md
          sed -i "s/{VISITS}/$VISITS/" README.md
          
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update traffic stats"
          git push

